apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datareporter.scheduledWorker.fullname" . }}
  labels:
    {{- include "datareporter.labels" . | nindent 4 }}
    app.kubernetes.io/component: scheduledworker
spec:
  replicas: {{ .Values.scheduledWorker.replicaCount }}
  selector:
    matchLabels:
      {{- include "datareporter.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: scheduledworker
  template:
    metadata:
      labels:
        {{- include "datareporter.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: scheduledworker
        {{- if .Values.scheduledWorker.podLabels }}
        {{- tpl (toYaml .Values.scheduledWorker.podLabels) $ | nindent 8 }}
        {{- end }}
      {{- if .Values.scheduledWorker.podAnnotations }}
      annotations:
      {{ toYaml .Values.scheduledWorker.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "datareporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.scheduledWorker.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "datareporter.name" . }}-scheduledworker
          securityContext:
            {{- toYaml .Values.scheduledWorker.securityContext | nindent 12 }}
          image: "{{ include "base.images.image" ( dict  "imageRoot" .Values.datareporter.image "global" .Values.global  "Values" .Values  "Chart" .Chart ) }}"
          imagePullPolicy: "{{ include "base.images.pullPolicy" ( dict  "imageRoot" .Values.datareporter.image "global" .Values.global  "Values" .Values ) }}"
          command: ["/bin/sh"]
          args: ["-c", ". /config/dynamicenv.sh && /app/bin/docker-entrypoint worker"]
          volumeMounts:
            - name: config
              mountPath: /config
            {{- with .Values.scheduledWorker.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
          {{- include "datareporter.env" . | nindent 12 }}
          {{- range $key, $value := .Values.scheduledWorker.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
          {{- end }}
          envFrom:
          {{- include "datareporter.envFrom" . | nindent 12 }}
          resources:
{{ toYaml .Values.scheduledWorker.resources | indent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "datareporter.fullname" . }}
        {{- with .Values.scheduledWorker.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    {{- if .Values.scheduledWorker.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.scheduledWorker.nodeSelector | indent 8 }}
    {{- end }}
    {{- with .Values.scheduledWorker.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.scheduledWorker.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
