{{- if not .Values.datareporter.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datareporter.fullname" . }}
  labels:
    {{- include "datareporter.labels" . | nindent 4 }}
type: Opaque
data:
  ## Start primary Redash configuration
  {{ $null := required "A value for one of the following variables is required: datareporter.secretKey (secure random value), datareporter.existingSecret (secret name)" (or .Values.datareporter.secretKey .Values.datareporter.existingSecret) }}
  secretKey: {{ default "" .Values.datareporter.secretKey | b64enc | quote }}
  googleClientSecret: {{ default "" .Values.datareporter.googleClientSecret | b64enc | quote }}
  ldapBindDnPassword: {{ default "" .Values.datareporter.ldapBindDnPassword | b64enc | quote }}
  {{ $null := required "A value for one of the following variables is required: datareporter.cookieSecret (secure random value), datareporter.existingSecret (secret name)" (or .Values.datareporter.cookieSecret .Values.datareporter.existingSecret) }}
  cookieSecret: {{ default "" .Values.datareporter.cookieSecret | b64enc | quote }}
  mailPassword: {{ default "" .Values.datareporter.mailPassword | b64enc | quote }}
  ## End primary Redash configuration
{{- end -}}