apiVersion: v1
kind: Service
metadata:
  name: {{ include "datareporter.fullname" . }}
  labels:
    {{- include "datareporter.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.service.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.server.httpPort }}
      protocol: TCP
      name: http
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  selector:
    {{- include "datareporter.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
