apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datareporter.fullname" . }}
  labels:
    {{- include "datareporter.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "datareporter.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        {{- include "datareporter.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: server
        {{- if .Values.server.podLabels }}
        {{- tpl (toYaml .Values.server.podLabels) $ | nindent 8 }}
        {{- end }}
      {{- if .Values.server.podAnnotations }}
      annotations:
      {{ toYaml .Values.server.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "datareporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "datareporter.name" . }}-server
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "{{ include "base.images.image" ( dict  "imageRoot" .Values.datareporter.image "global" .Values.global  "Values" .Values  "Chart" .Chart ) }}"
          imagePullPolicy: "{{ include "base.images.pullPolicy" ( dict  "imageRoot" .Values.datareporter.image "global" .Values.global  "Values" .Values ) }}"
          command: ["/bin/sh"]
          args: ["-c", ". /config/dynamicenv.sh && /app/bin/docker-entrypoint server"]
          volumeMounts:
            - name: config
              mountPath: /config
            {{- with .Values.server.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
          {{- include "datareporter.env" . | nindent 12 }}
          {{- range $key, $value := .Values.server.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
          {{- end }}
          envFrom:
          {{- include "datareporter.envFrom" . | nindent 12 }}
          ports:
            - containerPort: {{ .Values.server.httpPort }}
          livenessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.server.httpPort }}
            # Redash can take a while to come up initially, so we delay checks.
            initialDelaySeconds: 90
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.server.httpPort }}
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
{{ toYaml .Values.server.resources | indent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "datareporter.fullname" . }}
        {{- with .Values.server.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    {{- with .Values.server.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.server.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.server.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
