apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redash.fullname" . }}-plywood
  labels:
    {{- include "redash.labels" . | nindent 4 }}
    app.kubernetes.io/component: plywood
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "redash.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "redash.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "redash.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-plywood
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ include "base.images.image" (merge ( dict  "imageRoot" .Values.plywood.image "global" .Values.global  ) . ) }}"
          imagePullPolicy: "{{ include "base.images.pullPolicy" ( dict  "imageRoot" .Values.plywood.image "global" .Values.global  "Values" .Values ) }}"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/status
              port: http
          readinessProbe:
            httpGet:
              path: /api/v1/status
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
