name: Release Charts

on:
  push:
    branches:
      - feautre/chart-release-workflow

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git fetch --tags
          git branch --track master origin/master
          git describe --tags --abbrev=0 HEAD~

      - name: Install Helm
        uses: azure/setup-helm@v3
      - name: Update Repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        id: release
        with:
          version: v1.6.1
          charts_dir: ./charts
          pages_branch: gh-pages
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Changes
        run: |
          echo ${{join(steps.release.outputs.*, '\n')}}
